apiVersion: 1

datasources:
  - name: StockData-TimescaleDB
    type: postgres
    access: proxy
    url: postgres-timescale:5432
    database: stockdata
    user: grafana
    secureJsonData:
      password: 'grafana'
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 20
      maxIdleConns: 5
      connMaxLifetime: 14400
      timescaledb: true
    isDefault: true
    editable: true

  - name: StockData-Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true

